import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const runner = await readFile(new URL('../scripts/e2e-mvp-local.mjs', import.meta.url), 'utf8');
const launcher = await readFile(new URL('../scripts/e2e-mvp-local.ps1', import.meta.url), 'utf8');

test('el E2E exige confirmación y bloquea usuarios o tenants que no sean el LEGACY vacío de migración', () => {
  assert.ok(launcher.includes('$SupabaseWorkdir = $repo'));
  assert.ok(launcher.includes("Join-Path $PSScriptRoot '..'"));
  assert.ok(!launcher.includes('downtimeos-supabase-check-17e0d9c049a54fb4b73727f6c11b5df4'));
  assert.ok(launcher.includes('[switch]$ConfirmDisposableDatabase'));
  assert.ok(!launcher.includes('$Stack'));
  assert.ok(launcher.includes("@('status', '--output', 'env', '--workdir', $SupabaseWorkdir)"));
  assert.ok(!launcher.includes('--output-format'));
  assert.ok(launcher.includes('[int]$ExpectedSupabasePort = 54321'));
  assert.ok(launcher.includes('$apiUri.Port -ne $ExpectedSupabasePort'));
  assert.ok(launcher.includes('if (-not $ConfirmDisposableDatabase)'));
  assert.ok(launcher.includes('Confirma que Supabase Local está vacío'));
  assert.ok(runner.includes("MVP_E2E_DATABASE_DISPOSABLE !== '1'"));
  assert.ok(runner.includes('if (existingAuth.users.length)'));
  assert.ok(runner.includes("existingOrganizations[0]?.nombre === 'Histórico DowntimeOS'"));
  assert.ok(runner.includes('TABLAS_CON_DATOS_TENANT_E2E'));
  assert.ok(runner.includes('BUCKETS_CON_ARCHIVOS_TENANT_E2E'));
  assert.ok(runner.includes('verificación de datos previos en ${table}'));
  assert.ok(runner.includes('verificación de archivos en Storage ${bucket}'));
  assert.ok(runner.includes('validarBaseE2E({'));
  assert.ok(runner.indexOf('if (existingAuth.users.length)') < runner.indexOf('const suffix = randomUUID()'));
  assert.ok(runner.indexOf('validarBaseE2E({') < runner.indexOf('const suffix = randomUUID()'));
  assert.ok(runner.indexOf('validarBaseE2E({') < runner.indexOf('async function createCompany'));
  assert.ok(runner.includes("confirmFromEmail(env.mailpit, email, supabaseOrigin, appOrigin, 'signup')"));
  assert.ok(runner.includes("confirmacion.redirect.pathname, '/activar'"));
  assert.ok(runner.includes('GET /api/cuenta tras confirmar registro ${label}'));
  assert.ok(runner.includes("assert.deepEqual(registrationData, { ok: true, siguiente: 'confirmar_o_iniciar_sesion' }"));
  assert.ok(runner.includes('async function localAuthUserId(authApi, adminHeaders, supabaseOrigin, email)'));
  assert.ok(runner.includes("new URL('admin/users?page=1&per_page=100', authApi)"));
  assert.ok(!runner.includes('registrationData.registro?.usuario?.id'));
  assert.ok(runner.includes('confirmación del registro del titular desde el correo real de Mailpit'));
  assert.ok(runner.includes('async function assertPostgrestMutationDenied'));
  assert.ok(runner.includes('JWT autenticado no puede ${method} planta_lineas directamente'));
  assert.ok(runner.includes('JWT anon no puede ${method} planta_lineas directamente'));
  assert.ok(launcher.includes("$env:SUPABASE_ANON_JWT_KEY = $settings.ANON_KEY"));
  assert.ok(!runner.includes('pruebas directas de mutación INSERT/UPDATE/DELETE con JWT'));
});
